### ISSUE TITLE
Greengrassのバージョンについて

### ISSUE THREAD

**Issue by shuogawa** [aws-samples/aws-jp-iot-samples#2]
Greengrassを試したく
https://aws-iot-greengrass-for-beginners.workshop.aws/
を進めたのですが、
グループがクラシック(V1)の物が作成されました。
このハンズオンはGreengrass V1の物でしょうか？
Greengrass V2のハンズオンはございますか？

![image](https://user-images.githubusercontent.com/660998/106352942-4017a600-632a-11eb-8f98-61af583e3497.png)

**Comment by sparkgene** [comment]
ご指摘の通り、こちらのハンズオンはv1向けのものとなっております。v2のハンズオンも今後、公開予定です。英語版ですが、開発者ドキュメントに試す方法が紹介されていますので、こちらもご検討ください。https://docs.aws.amazon.com/ja_jp/greengrass/v2/developerguide/getting-started.html

**Comment by shuogawa** [comment]
ありがとうございました!
