### ISSUE TITLE
Opensearch Serviceの使用について

### ISSUE THREAD

**Issue by f-mio** [aws-samples/aws-jp-iot-samples#3]
# 質問内容

## 背景
AWS IoT Core 初級ハンズオンを進め、学習をしております。　　
【OpenSearch Service の作成】 > 【IoT ルールの作成】の部分でテキストに表示されていない部分がありまして、進め方についてご教示いただきたく書かせていただきました。  
iot-core-for-beginners.workshop.aws/phase5/step2.html

## 質問
Opensearchのドメイン作成を終え、IoTルールを定めているのですが、アクション選択時のリストに  
【Amazon Elasticsearch Serviceにメッセージを送信する】  
が、表示されず次に進めない状態です。  
Opensearchの使用、もしくは別のサービスを使用して可視化するための方法をご教示いただけないでしょうか？  
<img width="1118" alt="スクリーンショット 2021-09-22 20 34 54" src="https://user-images.githubusercontent.com/52245444/134336731-a8e91acc-2dc9-4ca0-9454-cd2204780f7d.png">

  
末筆となりましたが、貴重な学習資料をご提供いただき誠にありがとうございます。

**Comment by sparkgene** [comment]
ご迷惑をおかけしております。現在日本語の表示が正しく出ておらず、貼っていただいたスクリーンショットの中にあるactionBuilder.select.openSearchと表示されているアクションがOpensearch(旧Elasticsearch)のアクションとなりますので、このアクションを選択して次の手順へお進みください。

**Comment by f-mio** [comment]
ご連絡・ご回答ありがとうございます。
基礎的な内容で申し訳ありませんでした。
actionBuilder.select.openSearchで進めることができましたこと報告いたします。
