### ISSUE TITLE
AWS IoT Core 初級ハンズオン　2.2.7 プログラムのダウンロード　エラー

### ISSUE THREAD

**Issue by jota1crowd** [aws-samples/aws-jp-iot-samples#4]

**Comment by jota1crowd** [comment]
標記ハンズオンの2.2.7で、以下の状態となります。
どの様に対処したら良いでしょうか？
AWS初心者です。よろしくお願いします。

pi@raspberrypi:~/dummy_client $ wget https://awsj-iot-handson.s3-ap-northeast-1.amazonaws.com/aws-ioy-core-workshop/dummy_client/device_main_raspi.py -O device_
main.py
--2021-10-04 19:55:00--  https://awsj-iot-handson.s3-ap-northeast-1.amazonaws.com/aws-ioy-core-workshop/dummy_client/device_main_raspi.py
awsj-iot-handson.s3-ap-northeast-1.amazonaws.com (awsj-iot-handson.s3-ap-northeast-1.amazonaws.com) をDNSに問いあわせています... 52.219.136.55
awsj-iot-handson.s3-ap-northeast-1.amazonaws.com (awsj-iot-handson.s3-ap-northeast-1.amazonaws.com)|52.219.136.55|:443 に接続しています... 接続しました。
HTTP による接続要求を送信しました、応答を待っています... 403 Forbidden
2021-10-04 19:55:01 エラー 403: Forbidden。

**Comment by yuma-m** [comment]
@jota1crowd さま

入力された URL に誤りがあるようです (aws-io"y"-core-workshop)。
ハンズオン手順の URL を再度コピーして、お試しいただけませんか？

```bash
wget https://awsj-iot-handson.s3-ap-northeast-1.amazonaws.com/aws-iot-core-workshop/dummy_client/device_main_raspi.py -O device_main.py
```

**Comment by jota1crowd** [comment]
ご指摘の通り、URLの誤りを修正することで問題解消しました。
ありがとうございました。
