### ISSUE TITLE
AWS IoT Core 初級ハンズオン　5.3.2 Index pattern の設定で問題

### ISSUE THREAD

**Issue by jota1crowd** [aws-samples/aws-jp-iot-samples#5]
ハンズオンの手順に従って3. IoT Coreのセットアップの3.4 デバイスシャドウの確認まで正常に出来ましたが、
5項に移り、5.3.2 Index pattern の設定にて
Index Pattern name に timestamp と入力してもNext step ボタンが押せるようにならず、以下の表示が出ます。
The index pattern you've entered doesn't match any indices. You can match any of your 0 indices, below.

どうしたらよいでしょうか。
よろしくお願いします。

**Comment by sparkgene** [comment]
考えられることとして、以下の内容がありますので、確認してみてください。

1) ダミープログラムが動いておらず、データが書き込まれていない
2) IoT Ruleの設定が誤っており、OpenSearch Serviceにデータが届いていない

1)については、Cloud9(デバイス)上でプログラムが実行していることを確認してください
2)については、RuleのSQLが正しいかを確認してください

**Comment by jota1crowd** [comment]
1.デバイスは、ダミーではなくRaspberryPi で実行していて、
　3.3.2疎通テストでデータが来ていることを確認済みです。
2.RuleのSQLが正しいかを確認するとは、どこを確認したらよいでしょうか？
　5-2の手順を３回ほどやり直してみましたが、結果は変わりませんでした。

**Comment by sparkgene** [comment]
IoT Coreのログを有効にすると、何か情報が確認できると思いますので、こちらを参考にログをデバッグレベルにして、Ruleの実行ログを確認してみてください。

また、RuleのSQLをこちらに貼っていただくことはできますか？

**Comment by jota1crowd** [comment]
ログはこの様な状況でした。
{
    "timestamp": "2021-11-19 09:24:13.238",
    "logLevel": "ERROR",
    "traceId": "1dc904c6-9bbf-613f-34ea-8a3d2f3011b1",
    "accountId": "629255964461",
    "status": "Failure",
    "eventType": "RuleExecution",
    "clientId": "Yama-20211114",
    "topicName": "data/Yama-20211114",
    "ruleName": "Yama_20211116_es",
    "ruleAction": "OpenSearchAction",
    "resources": {
        "Endpoint": "https://xxxxxxxxxxxxxxxxx.ap-northeast-1.es.amazonaws.com",
        "Index": "timestamp",
        "Type": "timestamp",
        "DocumentId": "aec6177a-3d14-465e-9d88-4ec2ef57eee1"
    },
    "principalId": "a46fb38279085c5f3ced2aa9f66a0757d524ad589b40bc3802e15bf001b0894a",
    "details": "403 Forbidden"
}

SQLを貼ります。
select parse_time("yyyy-MM-dd'T'HH:mm:ss.SSSZ", timestamp()) as timestamp, * FROM 'data/Yama-20211114'

**Comment by sparkgene** [comment]
↑のログでエンドポイントのURLが見えてしまっているので、少し編集させていただきました。

エラーを見ると、403が発生していますので、以下の2つの点を確認してみてください。
- IoT RuleのActionの編集画面で、作成されたIAM Roleに更新してくださいみたいなメッセージが出ている場合は、そのボタンを押してください。これは、Rule作成後にOpenSearchのエンドポイントを変更した場合などに発生することがあります。
- OpenSearch Serviceのクラスタを作成する際のドメインのアクセスポリシーが正しく設定されていない可能性があります。手順通りに作成されているかを確認してみてください。https://aws-iot-core-for-beginners.workshop.aws/phase5/step1.html#514-ドメインアクセスポリシーの設定

**Comment by jota1crowd** [comment]
・IoTルールでIAMに関するメッセージは特に出ていません。
・5-1.OpenSerchServicenoの作成、5-2.ルールの作成を最初からやり直し、5-3.Openダッシュボード/kinabaの設定を行ったところ、 Index pattern の設定にてNext step ボタンが押せるようになり、IndexPatternの確認画面が出ました。
ところが、その先に進んでグラフの設定をしてUpdateボタンを押したところ、画面の中央に、No Result Found と出ます。
再度、メニューよりDiscoverをクリックすると、No results match your search criteria.　Expand your time range
One or more of the indices you’re looking at contains a date field. Your query may not match anything in the current time range, or there may not be any data at all in the currently selected time range. You can try changing the time range to one which contains data.　となってしまいます。。

**Comment by sparkgene** [comment]
ラズパイを利用しているとのことですが、初期値だとタイムゾーンがイギリスになっている可能性があります。OpenSearch Dashboardでデータを表示する期間を、1日など長めにするとどうでしょうか？

**Comment by jota1crowd** [comment]
ラズパイのタイムゾーンはJSTになっています。
OpenSearch Dashboardでデータを表示する期間を変更するにはどのようにしたらよいですか？

**Comment by sparkgene** [comment]
workshop手順の [5.3.8 グラフの設定 の画面](https://aws-iot-core-for-beginners.workshop.aws/phase5/step3.html#538-グラフの設定) の右上に `Last 15 minutes` と書かれていますが、この部分が表示する期間を変シュルコントロールになっています。
カレンダーのようなアイコンをクリックすると、詳細な日付の範囲が指定できます

**Comment by jota1crowd** [comment]
グラフ設定の右上のところをいろいろ変えてやって見たところ、Next 9 hours とすると現在のデータが表示出来る様になりました。ただ、グラフのX軸に表示される時刻がよく分からないのですが、例えば2021年11月21日 16：00 JST　にラズパイから送られて来ているデータが、OpenSerchServiceのグラフでは、01：00　にプロットされている様です。JSTをUTCにそのまま変換すると9時間戻って21日の7:00 になると思うのですが。。　あるいは、OpenSerchServiceがラズパイから送られてくる時刻をUTCだと思ってJSTに変換して9時間進めてしまっているのでしょうか？

**Comment by sparkgene** [comment]
ダミーのプログラムがtimestampを送る際に、タイムゾーンの情報を付けていないから、JSTをUTCと判断してしまっている様ですね。

**Comment by jota1crowd** [comment]
分かりました。そもそも、このハンズオンがUTC以外を使うことを想定していないと理解しました。
・ラズパイ側のプログラムを修正してタイムゾーン付の時刻を送る様にしたいのですが、YYYY-MM-DDThh:mm:ss+09:00 の形式にすれば良いでしょうか？
・IoTルールの方は、現状以下のSQLとなっていますが、こちらはどの様に修正したら良いでしょうか？
select parse_time("yyyy-MM-dd'T'HH:mm:ss.SSSZ", timestamp()) as timestamp, * from '自分のトピック名'

**Comment by jota1crowd** [comment]
ラズパイ側を　YYYY-MM-DDThh:mm:ss+09:00 で送信するように修正し、
IoTルールを　select parse_time("yyyy-MM-dd'T'HH:mm:ss.SSS+09:00", timestamp()) as timestamp, * FROM 'data/Yama-20211114'
と修正したら、グラフのX軸がJST時刻で表示される様になり、解決しました。
