### ISSUE TITLE
AWS IOT CORE 初級ハンズオン 4.5.4 疎通テスト

### ISSUE THREAD

**Issue by jota1crowd** [aws-samples/aws-jp-iot-samples#6]
これまで、IoT Core MQQTテストクライアントのところでトピックのフィルターを例題に倣って入力し、サブスクライブを押すとデバイスからのデータが見えていたのですが、最近、MQQTテストクライアントの画面が変わったためか、サブスクライブするを押しても従来の様な受信データの表示が出ません。どの様にすれば受信データを見られる様になるのでしょうか？

**Comment by sparkgene** [comment]
UIは新しくなっても同じようにMQTTのテストクライアントとして利用することができます。新しいUIでは、複数のTopicにサブスクライブしながら表示することができるようになっています。そのため、複数のTopicにサブスクライブしている場合は、見たい方のサブスクリプションを選択する必要があります。詳しくはこちらを参照してください。https://docs.aws.amazon.com/iot/latest/developerguide/view-mqtt-messages.html#view-mqtt-subscribe

**Comment by sparkgene** [comment]
その後アップデートが無いためcloseいたします。
