### ISSUE TITLE
2.2 Raspbery  Piのセットアップ

### ISSUE THREAD

**Issue by busho100** [aws-samples/aws-jp-iot-samples#8]
Raspbery  Pi  Zeroを使ってIoT Coreのセットアップを行っていますが、grove-lcdでつまずいています。

内容：
Raspbery Pi Zero で、grove-lcdの認識はできているようです。温・湿度は、ターミナルで確認できていますがディスプレイの表示ができません。
デバイスの初期不良も考え、別のデバイスで試しましたが結果は同じです。

**Comment by sparkgene** [comment]
何も表示されないとのことですが、何かエラーは出ていますでしょうか？

**Comment by busho100** [comment]
ご連絡、ありがとうございます。
エラーは表示されません。

Groveのアドレスを変更してみて、不適切なアドレスだとエラーになりますが、それ以外ではエラーはございません。

iPhoneから送信

**Comment by sparkgene** [comment]
ハンズオンのサンプルソースで　ではなく、デバイス販売元のサンプルを利用した場合は表示されますでしょうか？
https://wiki.seeedstudio.com/Grove-16x2_LCD_Series/

**Comment by busho100** [comment]
大変お世話になります。

お時間をとらせてしまい、申し訳ございません。
私の基本的な誤りが原因でした。
(raspberry piもaws IoTも初めてで、不調法でした)

「grove-16×2 LCD」を使用すべきところ、「grove-LCD」を取り寄せ使っていました。
この「grove-LCD」は入力電圧が5vでした。

しかしながら、raspberry pi zeroの出力は3.5vで
、出力と入力電圧の違いから、反応しなかったようです。

本日、「grove-16×2 LCD」を取り寄せ接続しましたところ、ハンズオンの写真に示されている通りに、温湿度が表示されました。

ご迷惑をお掛けし、お騒がせいたしましたこと、お詫び申し上げます。

今後とも、ご教授、お願いいたします。

iPhoneから送信

**Comment by sparkgene** [comment]
解決したとのことで、良かったです！
